-- 자동차 종류가 '트럭'
-- 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명: FEE)
--  대여 기록 ID와 대여 금액 리스트를 출력
--  대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬

# SELECT HISTORY_ID, 
# CASE
#     WHEN (DATEDIFF(END_DATE, START_DATE) + 1) < 7 
#     THEN FLOOR(R.DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1))
    
#     WHEN (DATEDIFF(END_DATE, START_DATE) + 1) BETWEEN 7 AND 29 
#     THEN FLOOR(R.DAILY_FEE * 0.95 * (DATEDIFF(END_DATE, START_DATE) + 1))
    
#     WHEN (DATEDIFF(END_DATE, START_DATE) + 1) BETWEEN 30 AND 89 
#     THEN FLOOR(R.DAILY_FEE * 0.93 * (DATEDIFF(END_DATE, START_DATE) + 1))
    
#     WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 
#     THEN FLOOR(R.DAILY_FEE * 0.9 * (DATEDIFF(END_DATE, START_DATE) + 1))
#     END AS FEE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# JOIN 
# (
#     SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = '트럭'
# ) R USING(CAR_ID)
# ORDER BY 2 DESC, 1 DESC

SELECT H.HISTORY_ID, 
       FLOOR(R.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (1 - COALESCE(P.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR R ON H.CAR_ID = R.CAR_ID AND R.CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON R.CAR_TYPE = P.CAR_TYPE 
AND (
    (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30 AND P.DURATION_TYPE = '7일 이상') OR
    (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90 AND P.DURATION_TYPE = '30일 이상') OR
    (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 AND P.DURATION_TYPE = '90일 이상')
)
ORDER BY FEE DESC, H.HISTORY_ID DESC;
