-- 완료된 중고 거래
-- 총금액이 70만원 이상인 사람
-- 회원 ID, 닉네임, 총거래금액
-- 총 거래금액 기준 오름차순
# SELECT USER_ID, NICKNAME, TOTAL_SALES
# FROM USED_GOODS_USER G
# JOIN (
#     SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
#     FROM USED_GOODS_BOARD
#     WHERE STATUS = 'DONE'
#     GROUP BY WRITER_ID
# )

SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD B
    JOIN USED_GOODS_USER U ON(B.WRITER_ID = U.USER_ID)
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
    ORDER BY 3